name: Scheduled HelloPeter Scraper

on:
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run scraper
      env:
        # Database configuration - using SQLite for GitHub Actions
        DB_TYPE: sqlite
        DB_PATH: hellopeter_reviews.db
        
        # Fetch configuration
        BUSINESSES: bank-zero-mutual-bank,capitec-bank
        OUTPUT_FORMAT: json
        OUTPUT_DIR: output
        STATS_ONLY: "true"
        LOG_LEVEL: INFO
      run: |
        python cloud_fetch.py
        
    - name: Upload results
      uses: actions/upload-artifact@v3
      with:
        name: hellopeter-data
        path: |
          output/
          *.db
        retention-days: 7 